CREATE TABLE swap_quotes (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  destination_account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  market_id VARCHAR(320) CHARACTER SET ascii COLLATE ascii_bin NULL,
  provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  integrator VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_network_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  destination_network_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  sell_token VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  buy_token VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  sell_amount_raw DECIMAL(65,0) NOT NULL,
  buy_amount_raw DECIMAL(65,0) NOT NULL,
  minimum_buy_amount_raw DECIMAL(65,0) NOT NULL,
  sell_decimals TINYINT UNSIGNED NOT NULL,
  buy_decimals TINYINT UNSIGNED NOT NULL,
  slippage_bps SMALLINT UNSIGNED NOT NULL,
  price_impact_bps INT NULL,
  estimated_fee_raw DECIMAL(65,0) NULL,
  approval_address VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  provider_tool VARCHAR(100) NULL,
  provider_snapshot JSON NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  consumed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_swap_quotes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_swap_quotes_source_account FOREIGN KEY (source_account_id) REFERENCES wallet_accounts(id),
  CONSTRAINT fk_swap_quotes_destination_account FOREIGN KEY (destination_account_id) REFERENCES wallet_accounts(id),
  INDEX idx_swap_quotes_user_expiry (user_id, expires_at),
  INDEX idx_swap_quotes_request (user_id, request_hash, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE transaction_intents (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
  user_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  quote_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  parent_intent_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  idempotency_key VARCHAR(200) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  intent_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  chain_family VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  network_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  unsigned_transaction JSON NOT NULL,
  normalized_summary JSON NOT NULL,
  validation_result JSON NOT NULL,
  simulation_result JSON NOT NULL,
  payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  expires_at TIMESTAMP(6) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_transaction_intents_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_transaction_intents_account FOREIGN KEY (account_id) REFERENCES wallet_accounts(id),
  CONSTRAINT fk_transaction_intents_quote FOREIGN KEY (quote_id) REFERENCES swap_quotes(id),
  CONSTRAINT fk_transaction_intents_parent FOREIGN KEY (parent_intent_id) REFERENCES transaction_intents(id),
  CONSTRAINT uq_transaction_intent_idempotency UNIQUE (user_id, idempotency_key),
  CONSTRAINT chk_transaction_intent_status CHECK (status IN ('created','awaiting_approval','awaiting_signature','submitted','expired','failed','confirmed','unknown')),
  CONSTRAINT chk_transaction_intent_type CHECK (intent_type IN ('swap','erc20_approval')),
  INDEX idx_transaction_intents_user_status (user_id, status, created_at),
  INDEX idx_transaction_intents_expiry (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
